/// <reference types="node" />
/**
 * Interactive Setup Wizard
 * Guides users through PC Agent setup step by step
 */

import * as readline from 'readline';
import fs from 'fs';
import path from 'path';

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

function question(query: string): Promise<string> {
  return new Promise((resolve) => {
    rl.question(query, resolve);
  });
}

function validateIp(ip: string): boolean {
  const ipRegex = /^(\d{1,3}\.){3}\d{1,3}$/;
  if (!ipRegex.test(ip)) {
    return false;
  }
  const octets = ip.split('.').map(Number);
  return octets.every(octet => octet >= 0 && octet <= 255);
}

function validatePort(port: string): boolean {
  const num = parseInt(port, 10);
  return !isNaN(num) && num >= 1 && num <= 65535;
}

async function main() {
  console.log('🎯 PC Agent Setup Wizard\n');
  console.log('This wizard will help you configure the PC Agent step by step.\n');

  const config: Record<string, string> = {};

  // Step 1: Server Port
  console.log('📡 Step 1: Server Configuration');
  let port = await question('Enter server port (default: 3001): ');
  if (!port.trim()) {
    port = '3001';
  }
  while (!validatePort(port)) {
    console.error('   ❌ Invalid port. Must be between 1 and 65535.');
    port = await question('Enter server port (default: 3001): ');
    if (!port.trim()) {
      port = '3001';
      break;
    }
  }
  config.PORT = port;
  console.log(`   ✅ Port set to: ${port}\n`);

  // Step 2: Printer IP
  console.log('🖨️  Step 2: Printer Configuration');
  console.log('   You need to know your printer\'s IP address.');
  console.log('   Check your printer\'s network settings or router admin panel.\n');
  
  let printerIp = await question('Enter printer IP address (required): ');
  while (!printerIp.trim() || !validateIp(printerIp.trim())) {
    if (!printerIp.trim()) {
      console.error('   ❌ Printer IP is required!');
    } else {
      console.error('   ❌ Invalid IP address format. Use format: 192.168.1.100');
    }
    printerIp = await question('Enter printer IP address (required): ');
  }
  config.PRINTER_IP = printerIp.trim();
  console.log(`   ✅ Printer IP set to: ${printerIp.trim()}\n`);

  // Step 3: Printer Port
  let printerPort = await question('Enter printer port (default: 9100): ');
  if (!printerPort.trim()) {
    printerPort = '9100';
  }
  while (!validatePort(printerPort)) {
    console.error('   ❌ Invalid port. Must be between 1 and 65535.');
    printerPort = await question('Enter printer port (default: 9100): ');
    if (!printerPort.trim()) {
      printerPort = '9100';
      break;
    }
  }
  config.PRINTER_PORT = printerPort;
  console.log(`   ✅ Printer port set to: ${printerPort}\n`);

  // Step 4: Advanced Settings (Optional)
  console.log('⚙️  Step 3: Advanced Settings (Optional)');
  console.log('   Press Enter to use defaults.\n');

  let maxConnections = await question('Max connections per printer (default: 5): ');
  if (maxConnections.trim() && validatePort(maxConnections)) {
    config.MAX_PRINTER_CONNECTIONS = maxConnections.trim();
  }

  let logLevel = await question('Log level [debug|info|warn|error] (default: info): ');
  if (logLevel.trim() && ['debug', 'info', 'warn', 'error'].includes(logLevel.trim().toLowerCase())) {
    config.LOG_LEVEL = logLevel.trim().toLowerCase();
  }

  // Generate .env file
  console.log('\n📝 Generating .env file...\n');

  const envPath = path.join(process.cwd(), '.env');
  const envLines = [
    '# PC Agent Configuration',
    '# Generated by setup wizard',
    '',
    '# Server Configuration',
    `PORT=${config.PORT}`,
    '',
    '# Printer Configuration',
    `PRINTER_IP=${config.PRINTER_IP}`,
    `PRINTER_PORT=${config.PRINTER_PORT}`,
    '',
    '# Connection Pool Settings (Optional)',
  ];

  if (config.MAX_PRINTER_CONNECTIONS) {
    envLines.push(`MAX_PRINTER_CONNECTIONS=${config.MAX_PRINTER_CONNECTIONS}`);
  } else {
    envLines.push('# MAX_PRINTER_CONNECTIONS=5');
  }

  envLines.push(
    '# PRINTER_CONNECTION_TIMEOUT=5000',
    '# PRINTER_IDLE_TIMEOUT=30000',
    '',
    '# Logging Configuration',
  );

  if (config.LOG_LEVEL) {
    envLines.push(`LOG_LEVEL=${config.LOG_LEVEL}`);
  } else {
    envLines.push('LOG_LEVEL=info');
  }

  envLines.push(
    '# LOG_FILE=logs/pc-agent.log',
    '',
    '# CORS Configuration',
    'ALLOWED_ORIGINS=*',
  );

  const envContent = envLines.join('\n');

  // Check if .env exists
  if (fs.existsSync(envPath)) {
    const overwrite = await question('\n⚠️  .env file already exists. Overwrite? (y/N): ');
    if (overwrite.toLowerCase() !== 'y') {
      console.log('\n❌ Setup cancelled. .env file not modified.');
      rl.close();
      process.exit(0);
    }
  }

  fs.writeFileSync(envPath, envContent, 'utf-8');
  console.log('✅ .env file created successfully!\n');

  // Summary
  console.log('📋 Configuration Summary:');
  console.log(`   Server Port: ${config.PORT}`);
  console.log(`   Printer IP: ${config.PRINTER_IP}`);
  console.log(`   Printer Port: ${config.PRINTER_PORT}`);
  if (config.MAX_PRINTER_CONNECTIONS) {
    console.log(`   Max Connections: ${config.MAX_PRINTER_CONNECTIONS}`);
  }
  if (config.LOG_LEVEL) {
    console.log(`   Log Level: ${config.LOG_LEVEL}`);
  }
  console.log('');

  // Next steps
  console.log('🎉 Setup complete!\n');
  console.log('Next steps:');
  console.log('   1. Test printer connection: npm run test-printer');
  console.log('   2. Validate configuration: npm run validate-config');
  console.log('   3. Start PC Agent: npm start');
  console.log('   4. Check status: npm run check-status');
  console.log('   5. Install as service: npm run install-service (requires admin)');
  console.log('');

  rl.close();
}

main().catch((error) => {
  console.error('❌ Setup wizard error:', error);
  rl.close();
  process.exit(1);
});

