/// <reference types="node" />
/**
 * PC Agent Interactive CLI
 * Complete setup and management tool for PC Agent
 */

import * as readline from 'readline';
import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';
import dotenv from 'dotenv';
import { runSetupWizard, closeWizard, setReadlineInterface } from './wizard';

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});

// Share the readline interface with wizard to prevent duplicate input
setReadlineInterface(rl);

function question(query: string): Promise<string> {
  return new Promise((resolve) => {
    rl.question(query, resolve);
  });
}

function printHeader(title: string) {
  console.log('\n' + '='.repeat(60));
  console.log(`  ${title}`);
  console.log('='.repeat(60) + '\n');
}

function printSuccess(message: string) {
  console.log(`✅ ${message}`);
}

function printError(message: string) {
  console.error(`❌ ${message}`);
}

function printWarning(message: string) {
  console.log(`⚠️  ${message}`);
}

function printInfo(message: string) {
  console.log(`ℹ️  ${message}`);
}

// Check if running as administrator
function checkAdmin(): boolean {
  try {
    fs.accessSync('C:\\Windows\\System32\\config\\system', fs.constants.R_OK);
    return true;
  } catch {
    return false;
  }
}

// Check Node.js version
function checkNodeVersion(): boolean {
  try {
    const version = execSync('node --version', { encoding: 'utf-8' }).trim();
    const major = parseInt(version.replace('v', '').split('.')[0], 10);
    if (major >= 18) {
      printSuccess(`Node.js version: ${version}`);
      return true;
    } else {
      printError(`Node.js version ${version} is too old. Requires v18.0.0 or higher.`);
      return false;
    }
  } catch {
    printError('Node.js is not installed or not in PATH');
    return false;
  }
}

// Validate IP address
function validateIp(ip: string): boolean {
  const ipRegex = /^(\d{1,3}\.){3}\d{1,3}$/;
  if (!ipRegex.test(ip)) {
    return false;
  }
  const octets = ip.split('.').map(Number);
  return octets.every(octet => octet >= 0 && octet <= 255);
}

// Validate port
function validatePort(port: string): boolean {
  const num = parseInt(port, 10);
  return !isNaN(num) && num >= 1 && num <= 65535;
}

// Test printer connection
async function testPrinterConnection(printerIp: string, printerPort: number): Promise<boolean> {
  return new Promise((resolve) => {
    const { Socket } = require('net');
    const socket = new Socket();
    let resolved = false;
    const timeout = setTimeout(() => {
      if (!resolved) {
        resolved = true;
        socket.destroy();
        resolve(false);
      }
    }, 5000);

    socket.once('connect', () => {
      if (!resolved) {
        resolved = true;
        clearTimeout(timeout);
        socket.destroy();
        resolve(true);
      }
    });

    socket.once('error', () => {
      if (!resolved) {
        resolved = true;
        clearTimeout(timeout);
        resolve(false);
      }
    });

    try {
      socket.connect(printerPort, printerIp);
    } catch {
      if (!resolved) {
        resolved = true;
        clearTimeout(timeout);
        resolve(false);
      }
    }
  });
}

// Generate .env file
function generateEnvFile(config: Record<string, string>): void {
  const envPath = path.join(process.cwd(), '.env');
  const envLines = [
    '# PC Agent Configuration',
    '# Generated by Interactive CLI',
    '',
    '# Server Configuration',
    `PORT=${config.PORT}`,
    '',
    '# Printer Configuration',
    `PRINTER_IP=${config.PRINTER_IP}`,
    `PRINTER_PORT=${config.PRINTER_PORT}`,
    '',
    '# Connection Pool Settings',
    `MAX_PRINTER_CONNECTIONS=${config.MAX_PRINTER_CONNECTIONS || '5'}`,
    '# PRINTER_CONNECTION_TIMEOUT=5000',
    '# PRINTER_IDLE_TIMEOUT=30000',
    '',
    '# Logging Configuration',
    `LOG_LEVEL=${config.LOG_LEVEL || 'info'}`,
    '# LOG_FILE=logs/pc-agent.log',
    '',
    '# CORS Configuration',
    'ALLOWED_ORIGINS=*',
  ];

  fs.writeFileSync(envPath, envLines.join('\n'), 'utf-8');
}

// Main menu
async function showMainMenu(): Promise<void> {
  console.clear();
  console.log('\n');
  console.log('╔══════════════════════════════════════════════════════════╗');
  console.log('║     🎯 PC Agent - Interactive Management                 ║');
  console.log('╚══════════════════════════════════════════════════════════╝');
  console.log('');
  console.log('Select an option:');
  console.log('');
  console.log('  🚀 Setup & Configuration:');
  console.log('     1. Setup Wizard (Recommended for first time)');
  console.log('     2. Configure Settings');
  console.log('');
  console.log('  🧪 Testing & Diagnostics:');
  console.log('     3. Test Printer Connection');
  console.log('     4. Check Status');
  console.log('');
  console.log('  ⚙️  Service Management:');
  console.log('     5. Install as Windows Service');
  console.log('     6. Uninstall Windows Service');
  console.log('');
  console.log('  ▶️  Run Agent:');
  console.log('     7. Start Agent Manually');
  console.log('');
  console.log('  ❌ Exit');
  console.log('     8. Exit');
  console.log('');
}

// Complete setup - Use wizard
async function completeSetup(): Promise<void> {
  try {
    await runSetupWizard();
  } catch (error) {
    printError(`Setup wizard error: ${error instanceof Error ? error.message : String(error)}`);
  }
}

// Configure settings
async function configureSettings(): Promise<void> {
  printHeader('Configure Settings');

  const envPath = path.join(process.cwd(), '.env');
  let currentPort = '3001';
  let currentPrinterIp = '';
  let currentPrinterPort = '9100';
  let currentMaxConnections = '5';
  let currentLogLevel = 'info';

  // Load existing config if .env exists, otherwise use defaults
  if (fs.existsSync(envPath)) {
    dotenv.config({ path: envPath });
    currentPort = process.env.PORT || '3001';
    currentPrinterIp = process.env.PRINTER_IP || '';
    currentPrinterPort = process.env.PRINTER_PORT || '9100';
    currentMaxConnections = process.env.MAX_PRINTER_CONNECTIONS || '5';
    currentLogLevel = process.env.LOG_LEVEL || 'info';
  } else {
    printInfo('No .env file found. Using defaults. A new .env file will be created.');
  }

  console.log('Current configuration:');
  console.log(`   Server Port: ${currentPort}`);
  console.log(`   Printer IP: ${currentPrinterIp}`);
  console.log(`   Printer Port: ${currentPrinterPort}`);
  console.log(`   Max Connections: ${currentMaxConnections}`);
  console.log(`   Log Level: ${currentLogLevel}`);
  console.log('');

  // Server Port
  let port = await question(`Server port (current: ${currentPort}, press Enter to keep): `);
  if (!port.trim()) port = currentPort;
  while (!validatePort(port)) {
    printError('Invalid port. Must be 1-65535.');
    port = await question(`Server port (current: ${currentPort}): `);
    if (!port.trim()) port = currentPort;
  }

  // Printer IP
  let printerIp = await question(`Printer IP (current: ${currentPrinterIp}, press Enter to keep): `);
  if (!printerIp.trim()) printerIp = currentPrinterIp;
  while (!validateIp(printerIp.trim())) {
    printError('Invalid IP format. Use format: 192.168.1.100');
    printerIp = await question(`Printer IP (current: ${currentPrinterIp}): `);
    if (!printerIp.trim()) printerIp = currentPrinterIp;
  }
  printerIp = printerIp.trim();

  // Printer Port
  let printerPort = await question(`Printer port (current: ${currentPrinterPort}, press Enter to keep): `);
  if (!printerPort.trim()) printerPort = currentPrinterPort;
  while (!validatePort(printerPort)) {
    printError('Invalid port. Must be 1-65535.');
    printerPort = await question(`Printer port (current: ${currentPrinterPort}): `);
    if (!printerPort.trim()) printerPort = currentPrinterPort;
  }

  // Advanced
  let maxConnections = await question(`Max connections (current: ${currentMaxConnections}, press Enter to keep): `);
  if (!maxConnections.trim()) maxConnections = currentMaxConnections;

  let logLevel = await question(`Log level (current: ${currentLogLevel}, press Enter to keep): `);
  if (!logLevel.trim()) logLevel = currentLogLevel;

  // Save
  generateEnvFile({
    PORT: port,
    PRINTER_IP: printerIp,
    PRINTER_PORT: printerPort,
    MAX_PRINTER_CONNECTIONS: maxConnections.trim() || '5',
    LOG_LEVEL: logLevel.trim() || 'info',
  });

  printSuccess('Configuration updated!');
  printInfo('Restart the agent for changes to take effect.');
}

// Test printer
async function testPrinter(): Promise<void> {
  printHeader('Test Printer Connection');

  const envPath = path.join(process.cwd(), '.env');
  let printerIp = '';
  let printerPort = 9100;

  // Load from .env if exists, otherwise prompt
  if (fs.existsSync(envPath)) {
    dotenv.config({ path: envPath });
    printerIp = process.env.PRINTER_IP || '';
    printerPort = parseInt(process.env.PRINTER_PORT || '9100', 10);
    
    if (printerIp && printerIp !== '192.168.1.100') {
      printInfo(`Using configured printer: ${printerIp}:${printerPort}`);
    }
  }

  // If no printer IP configured, prompt for it
  if (!printerIp || printerIp === '192.168.1.100') {
    printInfo('Printer IP not configured or using default.');
    console.log('');
    printerIp = await question('Enter printer IP address to test: ');
    if (!printerIp.trim() || !validateIp(printerIp.trim())) {
      printError('Invalid or missing printer IP address.');
      return;
    }
    printerIp = printerIp.trim();
    
    const portInput = await question('Enter printer port (default: 9100): ');
    if (portInput.trim()) {
      if (!validatePort(portInput.trim())) {
        printError('Invalid port.');
        return;
      }
      printerPort = parseInt(portInput.trim(), 10);
    }
  }

  console.log('');
  printInfo(`Testing connection to ${printerIp}:${printerPort}...`);
  printInfo('This may take a few seconds...');
  console.log('');
  
  const connected = await testPrinterConnection(printerIp, printerPort);

  if (connected) {
    printSuccess('Printer connection successful!');
    console.log('');
    printInfo('Your printer is accessible and ready to receive print jobs.');
  } else {
    printError('Failed to connect to printer.');
    console.log('');
    console.log('🔍 Troubleshooting Guide:');
    console.log('');
    console.log('1. Verify Printer IP:');
    console.log('   - Check printer network settings');
    console.log('   - Verify IP address is correct');
    console.log('');
    console.log('2. Check Printer Status:');
    console.log('   - Ensure printer is powered on');
    console.log('   - Check printer is not in sleep mode');
    console.log('   - Verify printer is connected to network');
    console.log('');
    console.log('3. Network Connectivity:');
    console.log('   - Ensure PC and printer are on same network');
    console.log('   - Test with: ping ' + printerIp);
    console.log('   - Check router/firewall settings');
    console.log('');
    console.log('4. Port Configuration:');
    console.log('   - Default port for ESC/POS printers is 9100');
    console.log('   - Verify port is correct in printer settings');
    console.log('');
  }
}

// Install service
async function installService(): Promise<void> {
  printHeader('Install Windows Service');

  if (!checkAdmin()) {
    printError('Administrator privileges required!');
    printInfo('Please run this CLI as Administrator:');
    printInfo('  1. Right-click PowerShell/Command Prompt');
    printInfo('  2. Select "Run as Administrator"');
    printInfo('  3. Navigate to PC Agent folder');
    printInfo('  4. Run: npm run cli');
    return;
  }

  // Check if built
  const distPath = path.join(process.cwd(), 'dist', 'index.js');
  if (!fs.existsSync(distPath)) {
    printInfo('Building application first...');
    try {
      execSync('npm run build', { stdio: 'inherit' });
    } catch {
      printError('Build failed. Cannot install service.');
      return;
    }
  }

  try {
    printInfo('Installing Windows service...');
    execSync('node dist/scripts/install-service.js', { stdio: 'inherit' });
    printSuccess('Service installed successfully!');
  } catch {
    printError('Service installation failed.');
  }
}

// Uninstall service
async function uninstallService(): Promise<void> {
  printHeader('Uninstall Windows Service');

  if (!checkAdmin()) {
    printError('Administrator privileges required!');
    return;
  }

  const confirm = await question('⚠️  Are you sure you want to uninstall the service? (y/N): ');
  if (confirm.toLowerCase() !== 'y') {
    printInfo('Uninstallation cancelled.');
    return;
  }

  // Check if built
  const distPath = path.join(process.cwd(), 'dist', 'scripts', 'uninstall-service.js');
  if (!fs.existsSync(distPath)) {
    printInfo('Building application first...');
    try {
      execSync('npm run build', { stdio: 'inherit' });
    } catch {
      printError('Build failed.');
      return;
    }
  }

  try {
    printInfo('Uninstalling Windows service...');
    execSync('node dist/scripts/uninstall-service.js', { stdio: 'inherit' });
    printSuccess('Service uninstalled successfully!');
  } catch {
    printError('Service uninstallation failed.');
  }
}

// Check status
async function checkStatus(): Promise<void> {
  printHeader('Check Status');

  try {
    const axios = require('axios');
    // Load port from .env if exists, otherwise use default
    const envPath = path.join(process.cwd(), '.env');
    let port = '3001';
    if (fs.existsSync(envPath)) {
      dotenv.config({ path: envPath });
      port = process.env.PORT || '3001';
    } else {
      printInfo('No .env file found. Using default port 3001.');
    }
    
    printInfo(`Connecting to PC Agent at http://localhost:${port}...`);
    const response = await axios.get(`http://localhost:${port}/status`, { timeout: 3000 });
    const status = response.data;

    console.log('\n📊 Status Information:');
    console.log(`   Status: ${status.status || 'N/A'}`);
    console.log(`   Uptime: ${status.formattedUptime || 'N/A'}`);
    console.log(`   Version: ${status.version || 'N/A'}`);
    console.log('');
    console.log('📈 Statistics:');
    console.log(`   Total Print Jobs: ${status.statistics?.totalPrintJobs || 0}`);
    console.log(`   Successful: ${status.statistics?.successfulPrintJobs || 0}`);
    console.log(`   Failed: ${status.statistics?.failedPrintJobs || 0}`);
    if (status.successRate) {
      console.log(`   Success Rate: ${status.successRate}`);
    }
    console.log('');
    console.log('🏥 Health:');
    const overallHealth = status.health?.overall || 'N/A';
    const healthIcon = overallHealth === 'healthy' ? '✅' : overallHealth === 'degraded' ? '⚠️' : '❌';
    console.log(`   Overall: ${healthIcon} ${overallHealth}`);
    console.log(`   Server: ${status.health?.server || 'N/A'}`);
    console.log(`   Printer Pool: ${status.health?.printerPool || 'N/A'}`);
    
    if (status.statistics?.poolStatistics?.pools?.length > 0) {
      console.log('');
      console.log('🔌 Connection Pool:');
      status.statistics.poolStatistics.pools.forEach((pool: any) => {
        console.log(`   ${pool.printer}: ${pool.inUse}/${pool.connections} in use`);
      });
    }
    console.log('');

    if (overallHealth === 'healthy') {
      printSuccess('PC Agent is running and healthy!');
    } else {
      printWarning('PC Agent is running but health status is not optimal.');
    }
  } catch (error: any) {
    if (error.code === 'ECONNREFUSED') {
      printError('PC Agent is not running.');
      console.log('');
      printInfo('To start the agent:');
      console.log('   - Option 7: Start Agent Manually');
      console.log('   - Or run: npm start');
      console.log('');
      printInfo('To install as service:');
      console.log('   - Option 5: Install as Windows Service (requires admin)');
    } else {
      printError(`Failed to get status: ${error.message}`);
    }
  }
}

// Start agent
async function startAgent(): Promise<void> {
  printHeader('Start Agent Manually');

  const distPath = path.join(process.cwd(), 'dist', 'index.js');
  if (!fs.existsSync(distPath)) {
    printInfo('Building application first...');
    try {
      execSync('npm run build', { stdio: 'inherit' });
    } catch {
      printError('Build failed.');
      return;
    }
  }

  printInfo('Starting PC Agent...');
  printInfo('Press Ctrl+C to stop');
  console.log('');

  try {
    execSync('node dist/index.js', { stdio: 'inherit' });
  } catch (error: any) {
    if (error.signal === 'SIGINT') {
      printInfo('\nAgent stopped.');
    } else {
      printError(`Failed to start: ${error.message}`);
    }
  }
}

// Main CLI loop
async function main() {
  while (true) {
    await showMainMenu();
    const choice = await question('Enter your choice (1-8): ');

    switch (choice.trim()) {
      case '1':
        await completeSetup();
        break;
      case '2':
        await configureSettings();
        break;
      case '3':
        await testPrinter();
        break;
      case '4':
        await checkStatus();
        break;
      case '5':
        await installService();
        break;
      case '6':
        await uninstallService();
        break;
      case '7':
        await startAgent();
        break;
      case '8':
        console.log('\n👋 Goodbye!\n');
        closeWizard();
        rl.close();
        process.exit(0);
      default:
        printError('Invalid choice. Please enter 1-8.');
    }

    if (choice !== '8' && choice !== '1') {
      console.log('');
      await question('Press Enter to return to menu...');
    }
  }
}

// Run CLI
main().catch((error) => {
  printError(`Fatal error: ${error.message}`);
  rl.close();
  process.exit(1);
});

