/// <reference types="node" />
/**
 * Setup Wizard - Step-by-step interactive setup
 * Makes PC Agent setup easy and foolproof
 */

import * as readline from 'readline';
import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';
import dotenv from 'dotenv';

// Use a shared readline interface to avoid duplicate input
// If called from main CLI, it will pass its own interface
let rl: readline.Interface | null = null;

function getReadlineInterface(): readline.Interface {
  if (!rl) {
    rl = readline.createInterface({
      input: process.stdin,
      output: process.stdout,
    });
  }
  return rl;
}

function question(query: string): Promise<string> {
  return new Promise((resolve) => {
    getReadlineInterface().question(query, resolve);
  });
}

function printStep(step: number, total: number, title: string) {
  console.log(`\n${'='.repeat(60)}`);
  console.log(`Step ${step}/${total}: ${title}`);
  console.log('='.repeat(60));
}

function printSuccess(message: string) {
  console.log(`✅ ${message}`);
}

function printError(message: string) {
  console.error(`❌ ${message}`);
}

function printInfo(message: string) {
  console.log(`ℹ️  ${message}`);
}

function printWarning(message: string) {
  console.log(`⚠️  ${message}`);
}

function validateIp(ip: string): boolean {
  const ipRegex = /^(\d{1,3}\.){3}\d{1,3}$/;
  if (!ipRegex.test(ip)) return false;
  const octets = ip.split('.').map(Number);
  return octets.every(octet => octet >= 0 && octet <= 255);
}

function validatePort(port: string): boolean {
  const num = parseInt(port, 10);
  return !isNaN(num) && num >= 1 && num <= 65535;
}

async function testPrinterConnection(printerIp: string, printerPort: number): Promise<boolean> {
  return new Promise((resolve) => {
    const { Socket } = require('net');
    const socket = new Socket();
    let resolved = false;
    const timeout = setTimeout(() => {
      if (!resolved) {
        resolved = true;
        socket.destroy();
        resolve(false);
      }
    }, 5000);

    socket.once('connect', () => {
      if (!resolved) {
        resolved = true;
        clearTimeout(timeout);
        socket.destroy();
        resolve(true);
      }
    });

    socket.once('error', () => {
      if (!resolved) {
        resolved = true;
        clearTimeout(timeout);
        resolve(false);
      }
    });

    try {
      socket.connect(printerPort, printerIp);
    } catch {
      if (!resolved) {
        resolved = true;
        clearTimeout(timeout);
        resolve(false);
      }
    }
  });
}

function generateEnvFile(config: Record<string, string>): void {
  const envPath = path.join(process.cwd(), '.env');
  const envLines = [
    '# PC Agent Configuration',
    '# Generated by Setup Wizard',
    '',
    '# Backend Connection (Required)',
    `BACKEND_URL=${config.BACKEND_URL}`,
    `TENANT_ID=${config.TENANT_ID}`,
    '',
    '# Printer Configuration',
    `PRINTER_IP=${config.PRINTER_IP}`,
    `PRINTER_PORT=${config.PRINTER_PORT}`,
    '',
    '# Connection Pool Settings',
    `MAX_PRINTER_CONNECTIONS=${config.MAX_PRINTER_CONNECTIONS || '5'}`,
    '# PRINTER_CONNECTION_TIMEOUT=5000',
    '# PRINTER_IDLE_TIMEOUT=30000',
    '',
    '# Logging Configuration',
    `LOG_LEVEL=${config.LOG_LEVEL || 'info'}`,
    '# LOG_FILE=logs/pc-agent.log',
  ];

  fs.writeFileSync(envPath, envLines.join('\n'), 'utf-8');
}

function checkNodeVersion(): boolean {
  try {
    const version = execSync('node --version', { encoding: 'utf-8' }).trim();
    const major = parseInt(version.replace('v', '').split('.')[0], 10);
    return major >= 18;
  } catch {
    return false;
  }
}

function checkAdmin(): boolean {
  try {
    fs.accessSync('C:\\Windows\\System32\\config\\system', fs.constants.R_OK);
    return true;
  } catch {
    return false;
  }
}

export async function runSetupWizard(): Promise<void> {
  console.log('\n');
  console.log('╔══════════════════════════════════════════════════════════╗');
  console.log('║     🎯 PC Agent Setup Wizard                             ║');
  console.log('║     Complete setup in just a few steps                   ║');
  console.log('╚══════════════════════════════════════════════════════════╝');
  console.log('');

  // Step 1: Prerequisites
  printStep(1, 6, 'Checking Prerequisites');
  
  printInfo('Checking Node.js installation...');
  if (!checkNodeVersion()) {
    printError('Node.js 18+ is required but not found!');
    console.log('\nPlease install Node.js from: https://nodejs.org/');
    console.log('Then run this wizard again.\n');
    closeWizard();
    process.exit(1);
  }
  const nodeVersion = execSync('node --version', { encoding: 'utf-8' }).trim();
  printSuccess(`Node.js ${nodeVersion} detected`);

  // Step 2: Installation
  printStep(2, 6, 'Installing Dependencies');
  
  const nodeModulesExists = fs.existsSync(path.join(process.cwd(), 'node_modules'));
  if (!nodeModulesExists) {
    printInfo('Installing dependencies (this may take a minute)...');
    try {
      execSync('npm install', { stdio: 'inherit' });
      printSuccess('Dependencies installed successfully!');
    } catch {
      printError('Failed to install dependencies.');
      closeWizard();
      process.exit(1);
    }
  } else {
    printInfo('Dependencies already installed. Skipping...');
  }

  // Step 3: Configuration
  printStep(3, 6, 'Configuration');
  
  const envPath = path.join(process.cwd(), '.env');
  let config: Record<string, string> = {};

  if (fs.existsSync(envPath)) {
    printInfo('Existing .env file found.');
    const overwrite = await question('Do you want to reconfigure? (y/N): ');
    if (overwrite.toLowerCase() !== 'y') {
      printInfo('Using existing configuration. Skipping configuration step.');
      dotenv.config({ path: envPath });
      config = {
        BACKEND_URL: process.env.BACKEND_URL || 'http://localhost:3000',
        TENANT_ID: process.env.TENANT_ID || '',
        PRINTER_IP: process.env.PRINTER_IP || '',
        PRINTER_PORT: process.env.PRINTER_PORT || '9100',
        MAX_PRINTER_CONNECTIONS: process.env.MAX_PRINTER_CONNECTIONS || '5',
        LOG_LEVEL: process.env.LOG_LEVEL || 'info',
      };
    } else {
      // Reconfigure
      config = await collectConfiguration();
    }
  } else {
    printInfo('No existing configuration found. Let\'s configure now.');
    config = await collectConfiguration();
  }

  // Step 4: Build
  printStep(4, 6, 'Building Application');
  
  printInfo('Building TypeScript application...');
  try {
    execSync('npm run build', { stdio: 'inherit' });
    printSuccess('Build completed successfully!');
  } catch {
    printError('Build failed. Please check for errors above.');
    closeWizard();
    process.exit(1);
  }

  // Step 5: Test Printer
  printStep(5, 6, 'Testing Printer Connection');
  
  if (config.PRINTER_IP && config.PRINTER_IP !== '192.168.1.100') {
    printInfo(`Testing connection to printer at ${config.PRINTER_IP}:${config.PRINTER_PORT}...`);
    const connected = await testPrinterConnection(config.PRINTER_IP, parseInt(config.PRINTER_PORT, 10));
    
    if (connected) {
      printSuccess('Printer connection successful!');
    } else {
      printWarning('Could not connect to printer.');
      console.log('\nPossible reasons:');
      console.log('   - Printer IP address is incorrect');
      console.log('   - Printer is powered off or not on network');
      console.log('   - PC and printer are on different networks');
      console.log('   - Firewall is blocking the connection');
      console.log('');
      
      const continueAnyway = await question('Continue anyway? You can test later. (y/N): ');
      if (continueAnyway.toLowerCase() !== 'y') {
        printInfo('Setup cancelled. Please fix printer connection and try again.');
        closeWizard();
        process.exit(0);
      }
    }
  } else {
    printWarning('Printer IP not configured or using default.');
    printInfo('You can configure it later using: npm run cli (option 2)');
  }

  // Step 6: Service Installation
  printStep(6, 6, 'Service Installation (Optional)');
  
  const isAdmin = checkAdmin();
  if (!isAdmin) {
    printWarning('Administrator privileges not detected.');
    printInfo('To install as Windows Service, run this wizard as Administrator.');
    printInfo('For now, you can start the agent manually with: npm start');
  } else {
    const installService = await question('Install PC Agent as Windows Service? (Y/n): ');
    if (installService.toLowerCase() !== 'n') {
      try {
        printInfo('Installing Windows service...');
        execSync('node dist/scripts/install-service.js', { stdio: 'inherit' });
        printSuccess('Service installed and started!');
        printInfo('PC Agent will start automatically on system boot.');
      } catch {
        printError('Service installation failed.');
        printInfo('You can install it later using: npm run cli (option 4)');
      }
    } else {
      printInfo('Skipping service installation.');
      printInfo('You can install it later using: npm run cli (option 4)');
    }
  }

  // Summary
  console.log('\n');
  console.log('╔══════════════════════════════════════════════════════════╗');
  console.log('║     ✅ Setup Complete!                                  ║');
  console.log('╚══════════════════════════════════════════════════════════╝');
  console.log('');
  console.log('📋 Configuration Summary:');
  console.log(`   Backend URL: ${config.BACKEND_URL}`);
  console.log(`   Tenant ID: ${config.TENANT_ID}`);
  if (config.PRINTER_IP && config.PRINTER_IP !== '192.168.1.100') {
    console.log(`   Printer: ${config.PRINTER_IP}:${config.PRINTER_PORT}`);
  } else {
    console.log(`   Printer: Not configured (using default)`);
  }
  console.log('');
  console.log('🎉 PC Agent is ready to use!');
  console.log('');
  console.log('📝 Next Steps:');
  console.log('   1. Start the agent: npm start');
  console.log('   2. Check status: npm run cli (option 6)');
  console.log('   3. View logs: logs/pc-agent.log');
  console.log('   4. Install as service (optional): npm run install-service');
  console.log('');
  console.log('💡 How It Works:');
  console.log('   - PC Agent connects to backend automatically (no port forwarding needed!)');
  console.log('   - Backend sends print jobs via Socket.IO');
  console.log('   - PC Agent prints to your local printer');
  console.log('');
  console.log('💡 Tips:');
  console.log('   - Run "npm run cli" anytime to manage the agent');
  console.log('   - Service will auto-start on boot (if installed)');
  console.log('   - Check logs for troubleshooting');
  console.log('   - No router configuration needed - it just works!');
  console.log('');
  
  // Note: Don't close the readline interface here if it was shared from main CLI
  // The main CLI will handle closing it
}

async function collectConfiguration(): Promise<Record<string, string>> {
  const config: Record<string, string> = {};

  console.log('\nLet\'s configure your PC Agent step by step.\n');

  // Backend URL
  console.log('🌐 Backend Connection:');
  printInfo('Enter your backend server URL (where Waiter backend is running)');
  printInfo('Example: http://194.195.87.213:3000 or http://localhost:3000');
  console.log('');
  
  let backendUrl = await question('Backend URL (default: http://localhost:3000): ');
  if (!backendUrl.trim()) backendUrl = 'http://localhost:3000';
  
  // Basic URL validation
  while (!backendUrl.trim().match(/^https?:\/\/.+/)) {
    printError('Invalid URL format. Use format: http://hostname:port or https://hostname:port');
    backendUrl = await question('Backend URL (default: http://localhost:3000): ');
    if (!backendUrl.trim()) backendUrl = 'http://localhost:3000';
  }
  config.BACKEND_URL = backendUrl.trim();
  printSuccess(`Backend URL set to: ${backendUrl.trim()}`);

  // Tenant ID
  console.log('\n🏢 Tenant Configuration:');
  printInfo('Enter your tenant ID (subdomain) from the Waiter Admin Panel');
  printInfo('This identifies which restaurant/tenant this PC Agent belongs to');
  console.log('');
  
  let tenantId = await question('Tenant ID (required): ');
  while (!tenantId.trim()) {
    printError('Tenant ID is required!');
    tenantId = await question('Tenant ID (required): ');
  }
  config.TENANT_ID = tenantId.trim();
  printSuccess(`Tenant ID set to: ${tenantId.trim()}`);

  // Printer IP
  console.log('\n🖨️  Printer Configuration:');
  printInfo('You need your printer\'s IP address.');
  printInfo('Check your printer\'s network settings or router admin panel.');
  console.log('');
  
  let printerIp = await question('Printer IP Address (required): ');
  while (!printerIp.trim() || !validateIp(printerIp.trim())) {
    if (!printerIp.trim()) {
      printError('Printer IP is required!');
    } else {
      printError('Invalid IP format. Use format: 192.168.1.100');
    }
    printerIp = await question('Printer IP Address (required): ');
  }
  printerIp = printerIp.trim();
  config.PRINTER_IP = printerIp;
  printSuccess(`Printer IP set to: ${printerIp}`);

  // Printer Port
  let printerPort = await question('Printer Port (default: 9100): ');
  if (!printerPort.trim()) printerPort = '9100';
  while (!validatePort(printerPort)) {
    printError('Invalid port. Must be between 1 and 65535.');
    printerPort = await question('Printer Port (default: 9100): ');
    if (!printerPort.trim()) printerPort = '9100';
  }
  config.PRINTER_PORT = printerPort;
  printSuccess(`Printer port set to: ${printerPort}`);

  // Advanced (optional)
  console.log('\n⚙️  Advanced Settings (Optional - press Enter for defaults):');
  const maxConnections = await question('Max connections per printer (default: 5): ');
  config.MAX_PRINTER_CONNECTIONS = maxConnections.trim() || '5';

  const logLevel = await question('Log level [debug|info|warn|error] (default: info): ');
  config.LOG_LEVEL = logLevel.trim() || 'info';

  // Generate .env
  printInfo('\nGenerating .env file...');
  generateEnvFile(config);
  printSuccess('.env file created!');

  return config;
}

/**
 * Get local IP address (private IP)
 */
function getLocalIp(): string | null {
  try {
    const os = require('os');
    const interfaces = os.networkInterfaces();
    for (const name of Object.keys(interfaces)) {
      for (const iface of interfaces[name] || []) {
        if (iface.family === 'IPv4' && !iface.internal) {
          return iface.address;
        }
      }
    }
  } catch {
    // Ignore errors
  }
  return null;
}

export function closeWizard(): void {
  if (rl) {
    rl.close();
    rl = null;
  }
}

/**
 * Set the readline interface (used when called from main CLI)
 * This prevents duplicate input handling
 */
export function setReadlineInterface(interfaceInstance: readline.Interface): void {
  rl = interfaceInstance;
}

